language: node_js
sudo: false
node_js:
  - 4
  - 6
  - 7
  - 8

after_success:
  - npm i coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && echo "Coverage data was sent to coveralls!"
