# http://www.appveyor.com/docs/appveyor-yml

# build version format
version: "{build}"

# what combinations to test
environment:
  matrix:
    - nodejs_version: 4
    - nodejs_version: 6

install:
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - cmd: npm test
